### ISSUE TITLE
Student dropdown does not fit screen anymore.

### ISSUE THREAD

**Issue by vsviridov** [lighthouse-labs/laser_shark#113]
My macbook runs at 1280x800, and in maximized browser window the drop down overflows the screen.
All new cohorts are at the bottom...

**Comment by davidvandusen** [comment]
Funny you should mention it. I'm actually working on improving the layout responsiveness right now. I'll let you know when I've got something ready so that you can test it.

**Comment by davidvandusen** [comment]
I think I misunderstood you originally. For this issue, we'll just sort the cohort list reverse chronologically.

**Comment by davidvandusen** [comment]
The change has been merged in to sort the cohorts in reverse, however, to properly fix the issue of them getting cut off we'll need to paginate the cohorts. This issue has been partially fixed with the new ordering, but I think there will be a full UI revamp before anyone gets around to implementing a "cohorts admin and switching" page. That being said, I'm going to mark this as wontfix and add a note to the Custom Design lane in Trello to ensure this isn't an issue in the redesign.

**Comment by davidvandusen** [comment]
The following card was created as a reminder for when doing the new navigation:

https://trello.com/c/GByFQFKc/198-make-sure-all-cohorts-are-accessible-to-teacher-for-switching-on-any-layout
